### PR TITLE
Arc42 template

### PR DESCRIPTION
**Pull request by FeU-aKlos**
its basically the arc42 template with the scripts for creating a pdf and html file of the documentation

### CODE REVIEW

**Comment by FlrnFrmm** [comment]
Please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for your commit message.

**Comment by FlrnFrmm** [comment]
Please [squash](https://www.git-tower.com/learn/git/faq/git-squash) all your commits into one for the PR.
That one PR should have a descriptive title and all the necessary information in the commit messages body.

**Comment by FlrnFrmm** [comment]
Please move the docs from `.docs` to `docs` or do you have a good reason tom hide the docs folder?

**Comment by FeU-aKlos** [comment]
> Please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for your commit message.

done

**Comment by FeU-aKlos** [comment]
> Please [squash](https://www.git-tower.com/learn/git/faq/git-squash) all your commits into one for the PR. That one PR should have a descriptive title and all the necessary information in the commit messages body.

done

**Comment by FeU-aKlos** [comment]
> Please move the docs from `.docs` to `docs` or do you have a good reason tom hide the docs folder?

done

**Review by FlrnFrmm — APPROVED** [review]

**Pull request merged**
